# Generated by Django 5.1.2 on 2024-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('bank_code', models.CharField(choices=[('KB', 'KB국민은행'), ('NH', 'NH농협은행'), ('IBK', 'IBK기업은행'), ('KA', '카카오뱅크')], max_length=3)),
                ('account_type', models.CharField(choices=[('SAVINGS', '입출금통장'), ('MINUS', '마이너스통장')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
