# Generated by Django 5.1.2 on 2024-11-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("nickname", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20, unique=True)),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("KB", "KB국민은행"),
                            ("NH", "NH농협은행"),
                            ("IBK", "IBK기업은행"),
                            ("KA", "카카오뱅크"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("SAVINGS", "입출금통장"), ("MINUS", "마이너스통장")],
                        max_length=10,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=255,
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[("ONLINE", "온라인 송금"), ("ATM", "ATM 거래")],
                        max_length=255,
                    ),
                ),
                ("details", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acconts_transactions_hitories",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
