# Generated by Django 5.1.2 on 2024-11-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "balance_after_transaction",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("transaction_detail", models.CharField(max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "현금"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTO", "자동이체"),
                            ("CARD", "카드결제"),
                        ],
                        max_length=10,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_transactions_histories",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
